const base = process.env.BASE_URL || 'http://87.107.190.74';
const pages = ['/', '/auth.html', '/account.html', '/payment.html', '/chart-analysis.html', '/crypto-chart.html', '/market-analysis', '/ai-crypto-chart-analysis', '/disclaimer.html', '/privacy.html', '/admin.html'];
const mustContain = {'/':['growthViewport','marketStats'],'/chart-analysis.html':['AI chart workspace','Analyze chart'],'/crypto-chart.html':['Live market intelligence','data-tf="15m"'],'/payment.html':['USDT TRC20','Verify & activate Premium'],'/market-analysis':['Crypto Market Analysis'],'/ai-crypto-chart-analysis':['AI Crypto Chart Analysis']};
async function get(path,options={}){const r=await fetch(base+path,{redirect:'manual',...options});return{status:r.status,text:await r.text()};}
for(const p of pages){const r=await get(p);if(r.status!==200)throw new Error(`PAGE ${p} HTTP ${r.status}`);for(const n of(mustContain[p]||[]))if(!r.text.includes(n))throw new Error(`PAGE ${p} missing ${n}`);}
async function json(path,allowed=[200]){const r=await get(path);if(!allowed.includes(r.status))throw new Error(`API ${path} HTTP ${r.status}: ${r.text.slice(0,300)}`);try{return{status:r.status,data:JSON.parse(r.text)}}catch{throw new Error(`API ${path} non-JSON`);}}
const h=await json('/api/health');if(!h.data.ok)throw new Error('health not ok');
const ready=await json('/api/ready');if(!ready.data.ready)throw new Error('ready not ok');
const directCg=await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=5&page=1&sparkline=false',{signal:AbortSignal.timeout(15000)});if(!directCg.ok)throw new Error('direct CoinGecko feed unavailable');const cgRows=await directCg.json();if(!Array.isArray(cgRows)||cgRows.length<5)throw new Error('direct CoinGecko feed invalid');
const directBinance=await fetch('https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=15m&limit=20',{signal:AbortSignal.timeout(15000)});if(!directBinance.ok)throw new Error('direct Binance feed unavailable');const binRows=await directBinance.json();if(!Array.isArray(binRows)||binRows.length<20)throw new Error('direct Binance feed invalid');
const root=await get('/');if(!root.text.includes('CoinGecko browser feed')||!root.text.includes('Binance browser feed'))throw new Error('browser fallback markers missing');
await json('/api/payment/status');await json('/api/payment/verification-engine');await json('/api/me',[401]);console.log('PRODUCTION SMOKE TEST PASSED');
