import vm from 'node:vm';
const base = process.env.BASE_URL || 'http://87.107.190.74';
const pages = ['/', '/auth.html', '/account.html', '/payment.html', '/chart-analysis.html', '/crypto-chart.html', '/market-analysis', '/ai-crypto-chart-analysis', '/disclaimer.html', '/privacy.html', '/admin.html'];
const mustContain = {'/':['growthViewport','marketStats'],'/chart-analysis.html':['AI chart workspace','Analyze chart'],'/crypto-chart.html':['Live market intelligence','data-tf="15m"'],'/payment.html':['USDT TRC20','Verify & activate Premium'],'/market-analysis':['Crypto Market Analysis'],'/ai-crypto-chart-analysis':['AI Crypto Chart Analysis']};
async function get(path,options={}){const r=await fetch(base+path,{redirect:'manual',...options});return{status:r.status,text:await r.text()};}
for(const p of pages){const r=await get(p);if(r.status!==200)throw new Error(`PAGE ${p} HTTP ${r.status}`);for(const n of(mustContain[p]||[]))if(!r.text.includes(n))throw new Error(`PAGE ${p} missing ${n}`);}
async function json(path,allowed=[200]){const r=await get(path);if(!allowed.includes(r.status))throw new Error(`API ${path} HTTP ${r.status}: ${r.text.slice(0,300)}`);try{return{status:r.status,data:JSON.parse(r.text)}}catch{throw new Error(`API ${path} non-JSON`);}}
const h=await json('/api/health');if(!h.data.ok)throw new Error('health not ok');
const coins=await json('/api/coins');if(!Array.isArray(coins.data.coins)||coins.data.coins.length<100)throw new Error('production market universe unavailable');if(!coins.data.coins.some(x=>x.symbol==='BTC'))throw new Error('BTC missing from market universe');const sample=coins.data.coins.find(x=>x.symbol==='BTC')||coins.data.coins[0];if(!Number.isFinite(Number(sample.price))||!Number.isFinite(Number(sample.volume24h)))throw new Error('production market rows missing live price/volume');if(!Number.isFinite(Number(sample.circulatingSupply)))throw new Error('production market rows missing circulating supply');const refreshed=await json('/api/coins?refresh=1');if(!Array.isArray(refreshed.data.coins)||refreshed.data.coins.length<100)throw new Error('forced market refresh unavailable');const stats=await json('/api/market-stats');if(!Number.isFinite(Number(stats.data.totalMarketCap))||!Number.isFinite(Number(stats.data.totalVolume24h))||stats.data.pricedAssets<100||stats.data.supplyTracked<100)throw new Error('production market stats unavailable');const ready=await json('/api/ready');if(!ready.data.ready)throw new Error('ready not ok');
const directCg=await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=5&page=1&sparkline=false',{signal:AbortSignal.timeout(15000)});if(!directCg.ok)throw new Error('direct CoinGecko feed unavailable');const cgRows=await directCg.json();if(!Array.isArray(cgRows)||cgRows.length<5)throw new Error('direct CoinGecko feed invalid');
const chartCg=await fetch('https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=1',{signal:AbortSignal.timeout(15000)});if(!chartCg.ok)throw new Error('direct CoinGecko chart unavailable');const chartData=await chartCg.json();if(!Array.isArray(chartData.prices)||chartData.prices.length<20)throw new Error('direct CoinGecko chart invalid');
const root=await get('/');if(!root.text.includes('500 tracked assets')||!root.text.includes('growthViewport')||!root.text.includes('marketStats')||!root.text.includes('marketVolume')||!root.text.includes('marketSupply'))throw new Error('dashboard production markers missing');const scripts=[...root.text.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);for(const s of scripts){try{new vm.Script(s,{filename:'dashboard-inline.js'})}catch(e){throw new Error('dashboard JavaScript syntax error at '+e.lineNumber+':'+e.columnNumber+': '+e.message)}}const chartPage=await get('/crypto-chart.html');if(!chartPage.text.includes('CoinGecko browser feed')||!chartPage.text.includes('Live market intelligence'))throw new Error('chart fallback markers missing');
const payStatus=await json('/api/payment/status');if(!payStatus.data.configured)throw new Error('payment configuration missing on production');const payConfig=await json('/api/payment/config');if(!Number.isFinite(Number(payConfig.data.amount))||Number(payConfig.data.amount)<=0)throw new Error('payment amount missing');if(!/^T[A-Za-z0-9]{33}$/.test(String(payConfig.data.wallet||'')))throw new Error('TRC20 wallet missing or invalid');if(payConfig.data.network!=='TRC20'||payConfig.data.asset!=='USDT')throw new Error('payment network/asset mismatch');await json('/api/payment/verification-engine');await json('/api/me',[401]);console.log('PRODUCTION SMOKE TEST PASSED');
